<template>
  <section class="page narrow-page">
    <PageHeader :title="title" :subtitle="subtitle" />
    <article class="panel account-panel"><h2>{{ heading }}</h2><p>{{ description }}</p><div v-if="kind === 'notifications'" class="notification-list"><div v-for="item in notifications" :key="item.title"><span class="status" :class="item.state">{{ item.type }}</span><div><strong>{{ item.title }}</strong><p>{{ item.description }}</p></div></div></div><template v-else><label v-for="field in fields" :key="field"><span>{{ field }}</span><input :value="values[field] || ''" :aria-label="field" /></label><button class="k-button k-button-solid k-button-solid-primary" type="button">Save changes</button></template></article>
  </section>
</template>
<script>
import PageHeader from "./PageHeader.vue";
export default { components: { PageHeader }, props: { kind: String }, computed: { title() { return { profile: "Your profile", settings: "Settings & preferences", help: "Help & support", notifications: "Notifications" }[this.kind]; }, subtitle() { return { profile: "Manage your warehouse account and contact details.", settings: "Control your workspace and notification preferences.", help: "Find warehouse guidance or contact the support team.", notifications: "Review recent operational updates and assignments." }[this.kind]; }, heading() { return this.kind === "help" ? "How can we help?" : this.title; }, description() { return this.kind === "help" ? "Search the warehouse knowledge base or send a support request with the affected order or SKU." : "Changes are saved only when you select Save changes."; }, fields() { return this.kind === "profile" ? ["First name", "Last name", "Email", "Role"] : this.kind === "settings" ? ["Default warehouse", "Report delivery email"] : ["Subject", "Order, PO, or SKU", "Message"]; }, values() { return { "First name": "Peter", "Last name": "Douglas", Email: "peter.douglas@coffeewarehouse.example", Role: "Operations manager", "Default warehouse": "Central warehouse" }; }, notifications() { return [{ type: "Warning", state: "warning", title: "PO-10482 missed its dock appointment", description: "Vale Verde Estates is one day late. Review the inbound delivery." }, { type: "Info", state: "success", title: "Morning shift closed above target", description: "Fulfilment completed 96.4% of orders before the cut-off." }]; } } };
</script>
