<template>
  <section class="page">
    <PageHeader :title="title" :subtitle="subtitle" updated="Last updated: 4 min ago" />
    <div class="kpi-grid compact">
      <article v-for="metric in metrics" :key="metric.label" class="kpi-card"><p>{{ metric.label }}</p><strong>{{ metric.value }}</strong><span :class="metric.state">{{ metric.detail }}</span></article>
    </div>
    <article class="panel table-panel">
      <div class="panel-header"><div><h2>{{ tableTitle }}</h2><p>{{ tableDescription }}</p></div><div class="panel-actions"><input v-model="search" type="search" :aria-label="`Search ${tableTitle}`" placeholder="Search records" /><button type="button" class="k-button k-button-solid k-button-solid-primary">Create record</button></div></div>
      <Grid :data-items="filteredRows" :columns="columns" :sortable="true" :resizable="true" :pageable="{ pageSizes: true, buttonCount: 5 }" :page-size="8" />
    </article>
  </section>
</template>

<script>
import { Grid } from "@progress/kendo-vue-grid";
import PageHeader from "./PageHeader.vue";
const configs = {
  inventory: { title: "Inventory management", subtitle: "Track stock levels, bin locations, and replenishment needs across every warehouse zone.", tableTitle: "Inventory overview", tableDescription: "Available stock and the latest movements by SKU.", metrics: [["TOTAL SKUS", "2,486", "Across 12 warehouse zones", "success"], ["LOW STOCK", "18", "Requires replenishment", "warning"], ["INVENTORY VALUE", "$1.84M", "At weighted average cost", "success"]], columns: ["SKU", "Description", "Available", "Bin location", "Status"], rows: [["BEA-ESP-1K", "Brazil Espresso Blend, 1 kg", "412", "A-12-04", "In stock"], ["GUA-ANT-25", "Guatemala Antigua, 25 kg", "18", "C-04-11", "Low stock"], ["KEN-AA-5K", "Kenya AA, 5 kg", "0", "B-07-03", "Out of stock"]] },
  "purchase-orders": { title: "Purchase orders", subtitle: "Manage procurement from supplier selection through receipt and reconciliation.", tableTitle: "Purchase order queue", tableDescription: "Open and recently received purchase orders.", metrics: [["OPEN ORDERS", "42", "9 awaiting approval", "warning"], ["DUE THIS WEEK", "11", "3 inbound today", "success"], ["AT RISK", "2", "Late supplier confirmation", "error"]], columns: ["PO number", "Supplier", "Expected delivery", "Total", "Status"], rows: [["PO-10482", "Vale Verde Estates", "25 Aug 2026", "$18,460", "Delayed"], ["PO-10491", "Sierra Azul Coffee", "27 Aug 2026", "$9,280", "Approved"], ["PO-10503", "Mombasa Exporters", "02 Sep 2026", "$26,940", "Submitted"]] },
  "sales-orders": { title: "Sales orders", subtitle: "Prioritize customer orders and move fulfilment from intake to delivery.", tableTitle: "Order queue", tableDescription: "Customer orders sorted by shipping commitment.", metrics: [["NEW ORDERS", "86", "17 placed in the last hour", "success"], ["RUSH ORDERS", "7", "Prioritize before 14:00", "warning"], ["ON HOLD", "3", "Payment or inventory review", "error"]], columns: ["Order", "Customer", "Ship-by", "Priority", "Status"], rows: [["SO-34082", "North Star Roasters", "25 Aug 2026", "Rush", "Processing"], ["SO-34089", "Linden Cafes", "26 Aug 2026", "High", "Packed"], ["SO-34101", "Fifth Street Market", "27 Aug 2026", "Standard", "New"]] },
  suppliers: { title: "Supplier management", subtitle: "Monitor supplier performance, contracts, and active procurement relationships.", tableTitle: "Supplier directory", tableDescription: "Lead time and fulfilment performance across active suppliers.", metrics: [["ACTIVE SUPPLIERS", "74", "6 strategic partners", "success"], ["ON-TIME DELIVERY", "93.2%", "Target: 95%", "warning"], ["CONTRACTS DUE", "4", "Renewal within 30 days", "warning"]], columns: ["Supplier", "Category", "Lead time", "On-time delivery", "Rating"], rows: [["Vale Verde Estates", "Green coffee", "18 days", "89%", "4.2 / 5"], ["Sierra Azul Coffee", "Green coffee", "12 days", "97%", "4.7 / 5"], ["Atlas Packaging", "Packaging", "7 days", "99%", "4.8 / 5"]] },
  planning: { title: "Team planning", subtitle: "Coordinate roster coverage and resource demand for warehouse shifts.", tableTitle: "Today's team roster", tableDescription: "Assigned employees and coverage for the current operating day.", metrics: [["SCHEDULED STAFF", "58", "Across three shifts", "success"], ["OPEN SHIFTS", "3", "Requires coverage", "warning"], ["CONFLICTS", "0", "No overlapping assignments", "success"]], columns: ["Employee", "Team", "Shift", "Zone", "Status"], rows: [["Elena Morris", "Fulfilment", "06:00 - 14:00", "Picking A", "On shift"], ["Malik Bowen", "Roasting", "07:00 - 15:00", "Roastery", "On shift"], ["Avery Kim", "Quality", "08:00 - 16:00", "Lab 2", "Scheduled"]] },
  operations: { title: "Warehouse operations", subtitle: "Monitor throughput, dock activity, and active floor assignments in real time.", tableTitle: "Active workers", tableDescription: "Current warehouse assignments and productivity signals.", metrics: [["PICKS / HOUR", "482", "Above shift target", "success"], ["PACKS / HOUR", "416", "Within 3% of target", "success"], ["DOCK APPOINTMENTS", "14", "2 arrivals remaining", "warning"]], columns: ["Worker", "Zone", "Current task", "Productivity", "Status"], rows: [["Taylor Reid", "Dock 3", "Unload PO-10482", "88%", "Awaiting arrival"], ["Maya Chen", "Picking B", "Pick SO-34082", "104%", "Active"], ["Jon Bell", "Packing", "Pack pallet 7", "97%", "Active"]] },
  assets: { title: "Asset management", subtitle: "Plan maintenance and protect the availability of essential warehouse equipment.", tableTitle: "Asset registry", tableDescription: "Service status and next maintenance due date.", metrics: [["ACTIVE ASSETS", "126", "Equipment in service", "success"], ["DUE IN 7 DAYS", "8", "Schedule maintenance", "warning"], ["OVERDUE", "2", "Requires immediate action", "error"]], columns: ["Asset ID", "Asset", "Location", "Next service", "Status"], rows: [["FLT-014", "Forklift 14", "Picking A", "20 Aug 2026", "Overdue"], ["CNV-008", "Conveyor line 8", "Packing", "28 Aug 2026", "Due soon"], ["RCK-112", "Racking bay 112", "Zone C", "15 Nov 2026", "Active"]] },
  manufacturing: { title: "Manufacturing planning", subtitle: "Schedule production, monitor work orders, and protect material availability.", tableTitle: "Work orders", tableDescription: "Active production work orders by line and due date.", metrics: [["ACTIVE WORK ORDERS", "16", "Across four production lines", "success"], ["MATERIAL SHORTAGES", "2", "Block start until resolved", "error"], ["LINE UTILIZATION", "84%", "Target: 80 - 90%", "success"]], columns: ["Work order", "Product", "Due date", "Line", "Status"], rows: [["WO-2081", "Espresso Blend 1 kg", "26 Aug 2026", "Line 1", "In progress"], ["WO-2089", "House Decaf 500 g", "28 Aug 2026", "Line 2", "Planned"], ["WO-2093", "Cold Brew 1 L", "30 Aug 2026", "Line 4", "QC"]] },
  finance: { title: "Financial reporting", subtitle: "Compare warehouse revenue, costs, and margin performance for the current period.", tableTitle: "Budget versus actual", tableDescription: "Operating spend by category for August 2026.", metrics: [["REVENUE", "$842K", "Up 6.8% versus July", "success"], ["GROSS MARGIN", "31.4%", "0.9 points above target", "success"], ["OPERATING COSTS", "$216K", "3.1% over budget", "warning"]], columns: ["Category", "Budget", "Actual", "Variance", "Status"], rows: [["Green coffee", "$268,000", "$274,600", "+$6,600", "Over budget"], ["Packaging", "$64,000", "$61,820", "-$2,180", "On budget"], ["Logistics", "$88,000", "$91,240", "+$3,240", "Over budget"]] },
};
export default {
  components: { Grid, PageHeader },
  props: { module: { type: String, required: true } },
  data() { return { search: "" }; },
  computed: {
    config() { return configs[this.module]; },
    title() { return this.config.title; }, subtitle() { return this.config.subtitle; }, tableTitle() { return this.config.tableTitle; }, tableDescription() { return this.config.tableDescription; },
    metrics() { return this.config.metrics.map(([label, value, detail, state]) => ({ label, value, detail, state })); },
    columns() { return this.config.columns.map((title, index) => ({ field: `field${index}`, title })); },
    filteredRows() { const query = this.search.toLowerCase(); return this.config.rows.filter((row) => row.join(" ").toLowerCase().includes(query)).map((row) => Object.fromEntries(row.map((value, index) => [`field${index}`, value]))); },
  },
};
</script>
