export default {
    build: {
      transpile: [
        "@progress/kendo-data-query",
        "@progress/kendo-drawing",
        "@progress/kendo-licensing",
        "@progress/kendo-vue-animation",
        "@progress/kendo-vue-charts",
        "@progress/kendo-vue-data-tools",
        "@progress/kendo-vue-dateinputs",
        "@progress/kendo-vue-dropdowns",
        "@progress/kendo-vue-excel-export",
        "@progress/kendo-vue-grid",
        "@progress/kendo-vue-indicators",
        "@progress/kendo-vue-inputs",
        "@progress/kendo-vue-intl",
        "@progress/kendo-vue-pdf",
        "@progress/kendo-vue-popup",
        "@progress/kendo-vue-labels",
        "@progress/kendo-vue-buttons",
        "@progress/kendo-vue-dialogs",
        "@progress/kendo-svg-icons",
        "@progress/kendo-date-math",
        "@progress/kendo-vue-layout",
        "@progress/kendo-vue-progressbars",
        "@progress/kendo-vue-treeview",
      ],
    },
  };
