# Builds and tests example applications
name: CI

on:
  push:
    branches-ignore:
      - master

env:
    NODE_OPTIONS: --max_old_space_size=16384

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Use NodeJS v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check out repository
        uses: actions/checkout@v4 

      - name: Build Coffee warehouse app
        working-directory: ./examples-standalone/coffee-warehouse
        run: |
          npm ci
          npm run build

      - name: Build Dashboard app
        working-directory: ./examples-standalone/dashboard
        run: |
          npm ci
          npm run build

      - name: Cleanup
        run: git clean -xdf

