# Builds and tests examples-standalone applications
name: CI

on:
  push:
    branches-ignore:
      - master

env:
  NODE_OPTIONS: --max_old_space_size=16384

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Use NodeJS v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get changed files
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            dashboard:
              - 'examples-standalone/dashboard/**'
            coffee-warehouse:
              - 'examples-standalone/coffee-warehouse/**'
            vue-personal-finance-nuxt:
              - 'examples-standalone/vue-personal-finance-nuxt/**'

      - name: Build Dashboard app
        working-directory: ./examples-standalone/dashboard
        if: steps.changes.outputs.dashboard == 'true'
        run: |
          npm ci
          npm run build

      - name: Build Vite Coffee warehouse app
        working-directory: ./examples-standalone/coffee-warehouse
        if: steps.changes.outputs.coffee-warehouse == 'true'
        run: |
            npm ci
            npm run build

      - name: Build Vue Personal Finance Nuxt app
        working-directory: ./examples-standalone/vue-personal-finance-nuxt
        if: steps.changes.outputs.vue-personal-finance-nuxt == 'true'
        run: |
          npm ci
          npm run build

      - name: Cleanup
        run: git clean -xdf

